name: az-func-node-cosmos-deployment
on: push

env:
  ENVIRONMENT: dev
  REGION: westus
  BRANCH: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo $GITHUB_REF
      - uses: actions/checkout@v2
        with:
          ref: ${{env.BRANCH}}
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{env.REGION}}
          template: ./deploy/main.bicep
          parameters: ./deploy/parameters.${{env.ENVIRONMENT}}.json
