name: az-func-node-cosmos-deployment
on: [workflow_dispatch]

env:
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - uses: azure/arm-deploy@v1
        with:
          template: ./deploy/main.bicep
          parameters: ./deploy/parameters.${{env.ENVIRONMENT}}.json  